export const JOBS_LOAD = "JOBS_LOAD";
export const JOBS_LOAD_SUCCESS = "JOBS_LOAD_SUCCESS";
export const JOBS_LOAD_ERROR = "JOBS_LOAD_ERROR";

export const CONFIGURATION_LOAD = "CONFIGURATION_LOAD";
export const CONFIGURATION_LOAD_SUCCESS = "CONFIGURATION_LOAD_SUCCESS";
export const CONFIGURATION_LOAD_ERROR = "CONFIGURATION_LOAD_ERROR";

export const JOB_SELECT = "JOB_SELECT";

export const JOB_DELETE = "JOB_DELETE";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_ERROR = "JOB_DELETE_ERROR";

export const MESSAGE_SEND = 'MESSAGE_SEND';