export const JOBS_LOAD = "JOBS_LOAD";
export const JOBS_LOAD_SUCCESS = "JOBS_LOAD_SUCCESS";
export const JOBS_LOAD_ERROR = "JOBS_LOAD_ERROR";

export const JOB_SELECT = "JOBS_SELECT";

export const JOB_TYPES_LOAD = "JOB_TYPES_LOAD";
export const JOB_TYPES_LOAD_SUCCESS = "JOB_TYPES_LOAD_SUCCESS";
export const JOB_TYPES_LOAD_ERROR = "JOB_TYPES_LOAD_ERROR";