on:
    issues:
        types: [opened]

jobs:
    comment-and-close:
        uses: dhis2/workflows-test/.github/workflows/comment-and-close.yml@main
        if: !contains(github.event.issues.sender.login , fromJson('["dhis2-bot", "kodiakhq", "dependabot"]'))
