on:
    issues:
        types: [opened]

jobs:
    comment-and-close:
        uses: ./.github/workflows/comment-and-close-reusable.yml
        if: !contains(github.event.issues.sender.login, fromJson('["dhis2-bot", "kodiakhq", "dependabot"]'))
