name: comment-and-close

on:
    issues:
        types: [opened]

jobs:
    comment-and-close:
        uses: dhis2/workflows-platform/.github/workflows/comment-and-close.yml@v1
        if: !contains(github.event.issues.sender.login , fromJson('["dhis2-bot", "kodiakhq", "dependabot"]'))
