name: deploy-production

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        uses: ./.github/workflows/deploy-production-reusable.yml
        secrets: inherit
