name: deploy-production

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        uses: dhis2/workflows-test/.github/workflows/deploy-production.yml@main
        secrets: inherit
        with:
            branch: master
