name: deploy-pr

on:
    pull_request:

concurrency:
    group: ${{ github.workflow}}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    deploy:
        uses: dhis2/workflows-test/.github/workflows/deploy-pr.yml@main
        if: '!github.event.pull_request.head.repo.fork'
        secrets: inherit
