on:
    workflow_call:
        secrets:
            CYPRESS_LOGIN_NAME:
                required: true
            CYPRESS_LOGIN_PASSWORD:
                required: true

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'
            - uses: cypress-io/github-action@v6
              with:
                  start: npx --yes @dhis2/cli-cluster up 2.41 --channel dev --db-version 2.41 --seed, yarn start:nobrowser
                  wait-on: 'http://localhost:8080/dhis-web-commons/security/login.action, http://localhost:3000'
                  wait-on-timeout: 600
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_LOGIN_NAME: ${{ secrets.CYPRESS_LOGIN_NAME }}
                  CYPRESS_LOGIN_PASSWORD: ${{ secrets.CYPRESS_LOGIN_PASSWORD }}
                  CYPRESS_LOGIN_SERVER: http://localhost:8080
            - run: npx --yes @dhis2/cli-cluster down 2.41
