on:
    workflow_call:

jobs:
    lint-commits:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile
            - id: commitlint
              run: echo ::set-output name=config_path::$(node -e "process.stdout.write(require('@dhis2/cli-style').config.commitlint)")
            - uses: wagoid/commitlint-github-action@v5
              with:
                  configFile: ${{ steps.commitlint.outputs.config_path }}
