name: test-and-release

on: push

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    # Cancel previous runs if not on a release branch
    cancel-in-progress: ${{ !contains(github.ref, fromJSON('["master", "main"]')) }}

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
    test:
        uses: ./.github/workflows/test.yml
    e2e:
        uses: ./.github/workflows/e2e.yml
        # Skips forks and dependabot PRs
        if: "!github.event.push.repository.fork"
        secrets: inherit
    release:
        needs: [lint, test, e2e]
        uses: ./.github/workflows/release.yml
        # Skips forks and dependabot PRs
        if: "!github.event.push.repository.fork"
        secrets: inherit
